### ISSUE TITLE
Course Schedule API inconsistency questions

### ISSUE THREAD

**Issue by volovikariel** [opendataConcordiaU/documentation#17]
I've noticed some things that look like inconsistencies, but I'm not sure if they are. 

Here's a response returned from calling the course schedule [BIOL/201 endpoint](https://opendata.concordia.ca/API/v1/course/schedule/filter/*/BIOL/201): 
```ts
{
  "courseID": "002625",
  "termCode": "2141",
  "session": "13W",
  "subject": "BIOL",
  "catalog": "201",
  "section": "50",
  "componentCode": "LEC",
  "componentDescription": "Lecture",
  "classNumber": "1161",
  "classAssociation": "1",
  "courseTitle": "INTRODUCTORY BIOLOGY",
  "topicID": "",
  "topicDescription": "",
  "classStatus": "Active",
  "locationCode": "LOY",
  "instructionModeCode": "P",
  "instructionModeDescription": "In Person",
  "meetingPatternNumber": "1",
  "roomCode": "CC320",
  "buildingCode": "CC",
  "room": "320",
  "classStartTime": "18.30.00",
  "classEndTime": "21.00.00",
  "modays": "N",
  "tuesdays": "Y",
  "wednesdays": "N",
  "thursdays": "N",
  "fridays": "N",
  "saturdays": "N",
  "sundays": "N",
  "classStartDate": "07/05/2014",
  "classEndDate": "19/08/2014",
  "career": "Undergraduate",
  "departmentCode": "BIOLOGY",
  "departmentDescription": "Biology",
  "facultyCode": "AS",
  "facultyDescription": "Faculty of Arts & Science",
  "enrollmentCapacity": "72",
  "currentEnrollment": "66",
  "waitlistCapacity": "0",
  "currentWaitlistTotal": "0",
  "hasSeatReserved": ""
}
```

1. `mondays` is misspelled as `modays`. Would it be possible to get this fixed?
![image](https://user-images.githubusercontent.com/16262535/205461326-d9d1915a-e386-445f-8c99-c3ce7700ac91.png)

1. In the [docs](https://github.com/opendataConcordiaU/documentation/blob/master/v1/courses/schedule.md#:~:text=The%20specific%20section%20letter%20or%20number%20of%20the%20scheduled%20class.) it marks the type of `section` as an `integer`.
![image](https://user-images.githubusercontent.com/16262535/205461219-e63d8c1a-4f18-4982-acbe-47a3958127a4.png)
But it's actually either a `string` (e.g: `04L`) or an `integer`, it should be marked as `string | integer` instead, shouldn't it?

1.  `hasSeatReserved` is marked as a `boolean`, but it's sometimes empty (neither Y nor N, just `""`), is there a reason why it doesn't default to `N`?

**Comment by opendataConcordiaU** [comment]
I will relay these questions to the data owners to see if if the know what is this about. Maybe they'll have an explanation or a fix for  it.

**Comment by volovikariel** [comment]
@opendataConcordiaU Any update? Just checking in~

**Comment by lib-development-concordiaU** [comment]
I'm sorry ... I haven't heard back from the team in charge of this. I will ask again

**Comment by volovikariel** [comment]
Any updates? ><

**Comment by opendataConcordiaU** [comment]
ohh .. the last new message that I got was that the enrolment issue was resolved. I assumed this was fine. Is still a happening ?

**Comment by volovikariel** [comment]
Point 4 and 5 seem to be  resolved - thank you :partying_face: 
Points 1, 2 and 3 points are still present
